# Generated by Django 4.2.1 on 2023-05-10 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New chapter', max_length=60)),
                ('summary', models.TextField(default='Summary...')),
                ('time_investment', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New photo', max_length=50)),
                ('alt', models.CharField(default='Alt photo', max_length=50)),
                ('url', models.FileField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='user', max_length=30)),
                ('email', models.CharField(default='default@webtelescope.com', max_length=40)),
                ('level', models.IntegerField(max_length=0)),
                ('xp', models.IntegerField(max_length=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New topic', max_length=60)),
                ('visits', models.IntegerField(default=0)),
                ('time_investment', models.IntegerField(default=0)),
                ('edit_date', models.DateTimeField()),
                ('difficulty', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='mainapp.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New test', max_length=50)),
                ('number_of_questions', models.IntegerField(default=0)),
                ('chapters', models.ManyToManyField(to='mainapp.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New section', max_length=60)),
                ('summary', models.TextField(default='Summary...')),
                ('time_investment', models.IntegerField(default=0)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_photo', to='mainapp.photo')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='mainapp.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='mainapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='New question')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='mainapp.photo')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mainapp.test')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New section', max_length=60)),
                ('text', models.TextField(default='Text...')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='mainapp.topic')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='mainapp.section'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='New answer')),
                ('is_correct', models.BooleanField(default=False)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='mainapp.photo')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mainapp.question')),
            ],
        ),
        migrations.CreateModel(
            name='TopicPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_photo', to='mainapp.photo')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_photo', to='mainapp.chapter')),
            ],
            options={
                'unique_together': {('photo', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='ParagraphPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph_photo', to='mainapp.paragraph')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraph_photo', to='mainapp.photo')),
            ],
            options={
                'unique_together': {('photo', 'paragraph')},
            },
        ),
        migrations.CreateModel(
            name='FavouritedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_topics', to='mainapp.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_topics', to='mainapp.userprofile')),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='CompletedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_topics', to='mainapp.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_topics', to='mainapp.userprofile')),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='ChapterPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_photo', to='mainapp.chapter')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_photo', to='mainapp.photo')),
            ],
            options={
                'unique_together': {('photo', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorship', to='mainapp.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorship', to='mainapp.userprofile')),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
